#!/usr/bin/env python3
"""check_docs — doc linter and index generator for bootstrap-kit projects.

Usage: check_docs.py [--fix] [--root PATH] [--stale-hours N]
Exit status 1 if any E-code finding, else 0. Warnings (W-codes) print but pass.

Codes (the CODES table below is the same list, for tooling):
  E001 cited file missing              E009 planned or active milestone without exit criteria
  E002 cited section missing           E010 moved pointer does not resolve
  E003 milestone index missing/stale   E011 file is not valid UTF-8
  E004 ADR index missing/stale         E012 config invalid; defaults used for the bad key
  E005 placeholder or TBD left in doc  E013 status outside its object's vocabulary
  E006 plan and feature disagree       E014 design doc header missing or status invalid
  E007 done milestone not complete     E015 design doc has no ## Changelog
  E008 depends on sketch/dropped/unknown  E016 phase rule broken
  W001 claim stale or unstamped        W004 milestone outside 3-10 features
  W002 in-progress plan, unticked dep  W005 evidence file not written yet
  W003 generated file differs          W006 AGENTS.md over 120 lines
  W007 cited project file not written yet (no CURRENT.md, bootstrap in progress)
"""
from __future__ import annotations

import argparse
import re
import sys
import tomllib
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path

GENERATED_MARKER = "<!-- generated by tools/check_docs.py --fix; do not edit by hand -->"

CODES: dict[str, str] = {
    "E001": "cited file missing",
    "E002": "cited section missing",
    "E003": "milestone index missing or stale",
    "E004": "ADR index missing or stale",
    "E005": "template placeholder or TBD left in doc",
    "E006": "plan status and feature checkbox disagree",
    "E007": "done milestone has unticked features or no evidence",
    "E008": "dependency on a sketch, dropped or unknown item",
    "E009": "planned or in-progress milestone without exit criteria",
    "E010": "moved pointer does not resolve",
    "E011": "file is not valid UTF-8",
    "E012": "config invalid; defaults used for the bad key",
    "E013": "status outside its object's vocabulary",
    "E014": "design doc header missing or status invalid",
    "E015": "design doc has no ## Changelog",
    "E016": "phase rule broken",
    "W001": "claim stale or unstamped",
    "W002": "in-progress plan with an unticked dependency",
    "W003": "generated file differs from --fix output",
    "W004": "milestone outside 3-10 features",
    "W005": "evidence file not written yet",
    "W006": "AGENTS.md over 120 lines",
    "W007": "cited project file not written yet (bootstrap in progress)",
}

# Tiers, least to most machinery. `minimal` is a project with no roadmap yet (mid-bootstrap):
# only citations and placeholders are checked. `full` runs everything `standard` runs.
TIERS = ("minimal", "lite", "standard", "full")
STANDARD_LIKE = ("standard", "full")

MILESTONE_STATUSES = ("sketch", "planned", "in progress", "done", "dropped")
PLAN_STATUSES = ("grounding", "planned", "in progress", "blocked", "done", "moved", "superseded")
PHASE_STATUSES = ("sketch", "active", "done")
ADR_STATUSES = ("proposed", "accepted", "rejected")  # plus `superseded by NNNN`
DESIGN_STATUSES = ("draft", "stable", "living")
MILESTONE_MIN_FEATURES, MILESTONE_MAX_FEATURES = 3, 10
AGENTS_MAX_LINES = 120
DEFAULT_EXCLUDE = (".git", "node_modules", ".venv", "__pycache__")
PLACEHOLDER_SCOPE_ROOT_FILES = ("AGENTS.md", "CLAUDE.md", "DOCS.md", "README.md")
ACTIVE_MILESTONE_STATUSES = ("planned", "in progress", "done")


# --------------------------------------------------------------------------- data


class UnreadableFile(Exception):
    """Raised by read_text when a file cannot be decoded as UTF-8."""

    def __init__(self, path: Path, reason: str):
        self.path = path
        self.reason = reason
        super().__init__(f"{path}: {reason}")


@dataclass
class Finding:
    code: str
    path: str
    line: int
    message: str

    @property
    def is_error(self) -> bool:
        return self.code.startswith("E")

    def __str__(self) -> str:
        return f"{self.path}:{self.line}: {self.code} {self.message}"


@dataclass
class Config:
    root: Path
    codename_placeholder: str | None = None
    stale_hours: float = 24
    allow_tbd_in: list[str] = field(default_factory=lambda: ["docs/OPEN-QUESTIONS.md"])
    citation_exclude: list[str] = field(default_factory=list)
    citation_roots: list[str] = field(default_factory=list)
    exclude: list[str] = field(default_factory=lambda: list(DEFAULT_EXCLUDE))
    tier: str = "auto"
    config_error: str | None = None

    @property
    def docs(self) -> Path:
        return self.root / "docs"


def load_config(root: Path) -> Config:
    cfg = Config(root=Path(root))
    path = cfg.docs / ".check_docs.toml"
    if path.exists():
        try:
            data = tomllib.loads(path.read_text(encoding="utf-8"))
        except tomllib.TOMLDecodeError as e:
            cfg.config_error = f"not valid TOML: {e}"
            return cfg
        for key in ("codename_placeholder", "stale_hours", "allow_tbd_in", "citation_exclude",
                    "citation_roots", "tier"):
            if key in data:
                setattr(cfg, key, data[key])
        if "exclude" in data:
            cfg.exclude = list(DEFAULT_EXCLUDE) + list(data["exclude"])
        if cfg.tier != "auto" and cfg.tier not in TIERS:
            cfg.config_error = f"tier must be one of {', '.join(TIERS)} or auto, not {cfg.tier!r}"
            cfg.tier = "auto"
        roots = cfg.citation_roots
        if not isinstance(roots, list) or not all(isinstance(r, str) for r in roots):
            cfg.config_error = "citation_roots must be a list of strings"
            cfg.citation_roots = []
        else:
            missing = [r for r in roots if not (cfg.root / r).is_dir()]
            if missing:
                cfg.config_error = f"citation_roots entry is not a directory: {missing[0]}"
                cfg.citation_roots = [r for r in roots if r not in missing]
    return cfg


# --------------------------------------------------------------------------- markdown helpers

HEADING_RE = re.compile(r"^(#{1,6})[ \t]+(.*?)[ \t]*$", re.M)
NUMBERED_RE = re.compile(r"^(\d+(?:\.\d+)*[a-z]?)\.?(?=\s)")
# A citation is `path/to/file.md` optionally followed by `§N.M`. The lookbehind rejects
# tokens glued to template braces, angle brackets, a hyphen, a slash, a dot, a colon or a
# dollar sign, so `{{x}}-design.md`, `M<n>.md`, `<file>.md`, `https://example.com/x.md` and
# `$ROOT/x.md` never match.
CITE_RE = re.compile(
    r"(?<![\w{}<>\-/.:$])((?:[\w.-]+/)*[A-Za-z0-9_][\w.-]*\.md)(?:[ \t]*§[ \t]*(\d+(?:\.\d+)*[a-z]?))?"
)
# The `[text]` of a markdown link is a label, not a citation; the `(target)` still is one.
LINK_TEXT_RE = re.compile(r"\[[^\]\n]*\](?=\()")
# A dotted anchor (§1.6) may point at a numbered list item inside a section, not only a heading.
DOTTED_ITEM_RE = re.compile(r"^[ \t]*(?:[-*][ \t]+)?(\d+(?:\.\d+)+[a-z]?)[.):]?(?=[ \t])", re.M)


def read_text(path: Path) -> str:
    try:
        text = path.read_bytes().decode("utf-8")
    except UnicodeDecodeError as e:
        raise UnreadableFile(path, f"file is not valid UTF-8: {e}") from e
    return text.replace("\r\n", "\n")


def rel(cfg: Config, path: Path) -> str:
    return path.resolve().relative_to(cfg.root.resolve()).as_posix()


def _excluded(cfg: Config, relpath: str) -> bool:
    parts = relpath.split("/")
    for e in cfg.exclude:
        e = e.strip("/")
        if "/" in e:
            if relpath == e or relpath.startswith(e + "/"):
                return True
        elif e in parts:
            return True
    return False


def iter_md(cfg: Config) -> list[Path]:
    return [p for p in sorted(cfg.root.rglob("*.md")) if not _excluded(cfg, rel(cfg, p))]


def line_of(text: str, pos: int) -> int:
    return text.count("\n", 0, pos) + 1


def numbered_headings(text: str) -> set[str]:
    out: set[str] = set()
    for m in HEADING_RE.finditer(text):
        n = NUMBERED_RE.match(m.group(2) + " ")
        if n:
            out.add(n.group(1))
    return out


def numbered_anchors(text: str) -> set[str]:
    """Headings plus dotted numbered list items: everything a `§N.M` citation may point at."""
    return numbered_headings(text) | {m.group(1) for m in DOTTED_ITEM_RE.finditer(text)}


def first_heading(text: str) -> str:
    m = HEADING_RE.search(text)
    return m.group(2).strip() if m else ""


def field_value(text: str, name: str) -> str | None:
    """Value of a `**Name:** value` line, or None if absent. Empty and dash values become ''."""
    m = re.search(rf"^\*\*{re.escape(name)}:\*\*[ \t]*(.*?)[ \t]*$", text, re.M)
    if not m:
        return None
    v = m.group(1).strip()
    return "" if v in ("", "—", "-", "n/a") else v


def section_body(text: str, title: str) -> str:
    """Body of the `## title` section, up to the next `## ` heading."""
    m = re.search(rf"^## {re.escape(title)}[ \t]*$\n?(.*?)(?=^## |\Z)", text, re.M | re.S)
    return m.group(1) if m else ""


# --------------------------------------------------------------------------- model


@dataclass
class Feature:
    id: str
    title: str
    ticked: bool
    moved_to: str | None
    plan_path: str | None
    depends_on: list[str]
    line: int


@dataclass
class Milestone:
    id: str
    path: Path
    title: str
    status: str
    exit_criteria: str
    evidence: str
    depends_on: list[str]
    features: list[Feature]

    def feature(self, fid: str) -> Feature | None:
        return next((f for f in self.features if f.id == fid), None)


@dataclass
class Plan:
    id: str
    path: Path
    title: str
    status: str
    moved_to: str | None
    milestone: str
    depends_on: list[str]
    stamps: list[tuple[datetime, str]]
    last_note: str
    tasks_open: int


@dataclass
class Adr:
    number: str
    path: Path
    title: str
    status: str


@dataclass
class Phase:
    id: str
    title: str
    status: str
    line: int
    milestones: list[str] = field(default_factory=list)
    exit: str = ""


@dataclass
class Roadmap:
    path: Path
    phases: list[Phase]
    milestone_titles: dict[str, str]
    sketch_ranges: list[tuple[int, int]]
    order: list[str]


MILESTONE_ID_RE = re.compile(r"M(\d+)")


def _milestone_sort_key(mid: str) -> tuple[int, str]:
    """Numeric key for a milestone ID; tolerates an ID that doesn't match M<digits>."""
    m = MILESTONE_ID_RE.fullmatch(mid)
    return (int(m.group(1)), "") if m else (10**9, mid)


@dataclass
class Project:
    cfg: Config
    tier: str
    md_files: list[Path]
    milestones: dict[str, Milestone]
    plans: dict[str, Plan]
    adrs: list[Adr]
    roadmap: Roadmap | None
    load_errors: list[Finding] = field(default_factory=list)

    def status_of(self, mid: str) -> str | None:
        if mid in self.milestones:
            return self.milestones[mid].status
        if self.roadmap and mid in self.roadmap.milestone_titles:
            return "sketch"
        return None

    def feature_of(self, fid: str) -> tuple[Milestone, Feature] | None:
        for m in self.milestones.values():
            f = m.feature(fid)
            if f:
                return m, f
        return None

    def milestone_order(self) -> list[str]:
        ordered = list(self.roadmap.order) if self.roadmap else []
        for mid in sorted(self.milestones, key=_milestone_sort_key):
            if mid not in ordered:
                ordered.append(mid)
        return ordered


# --------------------------------------------------------------------------- parsers

ID_LIST_RE = re.compile(r"\bM\d+(?:-\d+)?\b")
FEATURE_RE = re.compile(
    r"^- \[([ xX])\] (M\d+-\d+) — (.*?)(?: — `([^`]+)`)?(?: \(depends on: ([^)]*)\))?[ \t]*$", re.M
)
MOVED_FEATURE_RE = re.compile(r"^- ~~(M\d+-\d+) — (.*?)~~ moved to (M\d+-\d+)[ \t]*$", re.M)
SESSION_RE = re.compile(r"^- (\S+)(?: — ([^—\n]*?))?(?: — ([^\n]*))?[ \t]*$", re.M)
TASK_RE = re.compile(r"^- \[([ xX])\] T\d+", re.M)
ADR_FILE_RE = re.compile(r"^(\d{4})-.+\.md$")


def parse_ids(value: str | None) -> list[str]:
    return ID_LIST_RE.findall(value or "")


def _id_and_title(heading: str, pattern: str, fallback_id: str) -> tuple[str, str]:
    m = re.match(rf"({pattern})\s+—\s+(.*)$", heading)
    if m:
        return m.group(1), m.group(2).strip()
    return fallback_id, heading


def parse_milestone(path: Path) -> Milestone:
    text = read_text(path)
    mid, title = _id_and_title(first_heading(text), r"M\d+", path.stem)
    features: list[Feature] = []
    for m in FEATURE_RE.finditer(text):
        features.append(Feature(m.group(2), m.group(3).strip(), m.group(1) in "xX", None,
                                m.group(4), parse_ids(m.group(5)), line_of(text, m.start())))
    for m in MOVED_FEATURE_RE.finditer(text):
        features.append(Feature(m.group(1), m.group(2).strip(), False, m.group(3), None, [],
                                line_of(text, m.start())))
    features.sort(key=lambda f: f.line)
    return Milestone(
        id=mid, path=path, title=title,
        status=(field_value(text, "Status") or "").lower(),
        exit_criteria=field_value(text, "Exit criteria") or "",
        evidence=field_value(text, "Evidence of exit") or "",
        depends_on=parse_ids(field_value(text, "Depends on")),
        features=features,
    )


def parse_stamp(s: str) -> datetime | None:
    s = s.strip()
    if s.endswith("Z"):
        s = s[:-1] + "+00:00"
    try:
        dt = datetime.fromisoformat(s)
    except ValueError:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt


def parse_plan(path: Path) -> Plan:
    text = read_text(path)
    fallback = re.match(r"(M\d+-\d+)", path.stem)
    pid, title = _id_and_title(first_heading(text), r"M\d+-\d+", fallback.group(1) if fallback else path.stem)
    status_field = field_value(text, "Status") or ""
    status_raw = status_field.lower()
    moved_to = None
    status = status_raw
    if status_raw.startswith("moved"):
        status = "moved"
        ids = parse_ids(status_field) or parse_ids(field_value(text, "Moved to"))
        moved_to = ids[0] if ids else None
    stamps: list[tuple[datetime, str]] = []
    for m in SESSION_RE.finditer(section_body(text, "Sessions")):
        dt = parse_stamp(m.group(1))
        if dt:
            stamps.append((dt, (m.group(2) or "").strip()))
    notes = [ln[2:].strip() for ln in section_body(text, "Progress notes").splitlines() if ln.startswith("- ")]
    tasks_open = sum(1 for m in TASK_RE.finditer(section_body(text, "Tasks")) if m.group(1) == " ")
    milestone = field_value(text, "Milestone") or pid.split("-")[0]
    return Plan(pid, path, title, status, moved_to, milestone, parse_ids(field_value(text, "Depends on")),
                stamps, notes[-1] if notes else "", tasks_open)


def parse_adr(path: Path) -> Adr:
    text = read_text(path)
    number = ADR_FILE_RE.match(path.name).group(1)
    title = re.sub(r"^\d{4}\.\s*", "", first_heading(text)) or path.stem
    return Adr(number, path, title, (field_value(text, "Status") or "").lower())


def parse_roadmap(path: Path) -> Roadmap:
    text = read_text(path)
    lines = text.split("\n")
    heads = [(line_of(text, m.start()), len(m.group(1)), m.group(2).strip()) for m in HEADING_RE.finditer(text)]

    def section_end(idx: int) -> int:
        """Last line of the section including nested sub-headings."""
        level = heads[idx][1]
        for j in range(idx + 1, len(heads)):
            if heads[j][1] <= level:
                return heads[j][0] - 1
        return len(lines)

    def own_end(idx: int) -> int:
        """Last line before the next heading of any level: the section's own body only."""
        return heads[idx + 1][0] - 1 if idx + 1 < len(heads) else len(lines)

    def status_in(start: int, end: int) -> str:
        return (field_value("\n".join(lines[start - 1:end]), "Status") or "").lower()

    def exit_in(start: int, end: int) -> str:
        return field_value("\n".join(lines[start - 1:end]), "Exit") or ""

    phases: list[Phase] = []
    titles: dict[str, str] = {}
    sketch: list[tuple[int, int]] = []
    order: list[str] = []
    current: Phase | None = None
    for i, (ln, level, title) in enumerate(heads):
        pm = re.match(r"(P\d+)\s+—\s+(.*)$", title)
        mm = re.match(r"(M\d+)\s+—\s+(.*)$", title)
        end = section_end(i)
        if pm:
            current = Phase(pm.group(1), pm.group(2), status_in(ln, own_end(i)), ln,
                            exit=exit_in(ln, own_end(i)))
            phases.append(current)
            if current.status == "sketch":
                sketch.append((ln, end))
        elif mm:
            titles[mm.group(1)] = mm.group(2)
            order.append(mm.group(1))
            if current is not None and level > 2:
                current.milestones.append(mm.group(1))
            if status_in(ln, own_end(i)) == "sketch":
                sketch.append((ln, end))
        else:
            current = None if level <= 2 else current
    return Roadmap(path, phases, titles, sketch, order)


# --------------------------------------------------------------------------- loader


def detect_tier(cfg: Config) -> str:
    """The configured tier, or one detected from the file layout: `full` once the roadmap has
    two or more phases that are not sketches, `standard` with a milestones directory, `lite`
    with only a roadmap, `minimal` with neither."""
    if cfg.tier != "auto":
        return cfg.tier
    roadmap = cfg.docs / "roadmap.md"
    if (cfg.docs / "milestones").is_dir():
        if roadmap.is_file():
            try:
                phases = parse_roadmap(roadmap).phases
            except UnreadableFile:
                phases = []
            if sum(1 for p in phases if p.status in ("active", "done")) >= 2:
                return "full"
        return "standard"
    if roadmap.is_file():
        return "lite"
    return "minimal"


def load_project(cfg: Config) -> Project:
    tier = detect_tier(cfg)
    milestones: dict[str, Milestone] = {}
    plans: dict[str, Plan] = {}
    adrs: list[Adr] = []
    roadmap: Roadmap | None = None
    load_errors: list[Finding] = []
    if tier in STANDARD_LIKE:
        for p in sorted((cfg.docs / "milestones").glob("M*.md")):
            if not MILESTONE_ID_RE.fullmatch(p.stem):
                continue  # not a milestone file; still citation-checked as ordinary markdown
            try:
                m = parse_milestone(p)
            except UnreadableFile:
                load_errors.append(Finding("E011", rel(cfg, p), 1, "file is not valid UTF-8"))
                continue
            milestones[m.id] = m
        for p in sorted((cfg.docs / "plans").rglob("M*-*.md")):
            try:
                pl = parse_plan(p)
            except UnreadableFile:
                load_errors.append(Finding("E011", rel(cfg, p), 1, "file is not valid UTF-8"))
                continue
            plans[pl.id] = pl
    if tier in (*STANDARD_LIKE, "lite") and (cfg.docs / "roadmap.md").is_file():
        try:
            roadmap = parse_roadmap(cfg.docs / "roadmap.md")
        except UnreadableFile:
            load_errors.append(Finding("E011", rel(cfg, cfg.docs / "roadmap.md"), 1, "file is not valid UTF-8"))
    dec = cfg.docs / "decisions"
    if dec.is_dir():
        for p in sorted(dec.glob("*.md")):
            if not ADR_FILE_RE.match(p.name):
                continue
            try:
                adrs.append(parse_adr(p))
            except UnreadableFile:
                load_errors.append(Finding("E011", rel(cfg, p), 1, "file is not valid UTF-8"))
    return Project(cfg, tier, iter_md(cfg), milestones, plans, adrs, roadmap, load_errors)


# --------------------------------------------------------------------------- checks: citations


def _resolve_citation(cfg: Config, citing: Path, target: str) -> Path | None:
    bases = [citing.parent, cfg.root, cfg.docs] + [cfg.root / r for r in cfg.citation_roots]
    for base in bases:
        cand = base / target
        if cand.is_file():
            return cand
    return None


def _under_docs(cfg: Config, citing: Path, target: str) -> bool:
    """True for a citation a bootstrap step may still create: any path inside the project (the
    docs tree, the example instance folder, a sibling file). A path that escapes the project
    root is taken at face value and stays an error when missing."""
    return ".." not in target.split("/")


def check_citations(cfg: Config, md_files: list[Path]) -> list[Finding]:
    out: list[Finding] = []
    heading_cache: dict[Path, set[str]] = {}
    for path in md_files:
        r = rel(cfg, path)
        if any(r == x.strip("/") or r.startswith(x.strip("/") + "/") for x in cfg.citation_exclude):
            continue
        try:
            text = read_text(path)
        except UnreadableFile:
            out.append(Finding("E011", r, 1, "file is not valid UTF-8"))
            continue
        scan = LINK_TEXT_RE.sub(lambda lm: " " * len(lm.group(0)), text)
        lines = text.split("\n")
        unfinished_milestone = (r.startswith("docs/milestones/")
                                and (field_value(text, "Status") or "").lower() != "done")
        bootstrapping = not (cfg.docs / "CURRENT.md").is_file()
        for m in CITE_RE.finditer(scan):
            target, anchor = m.group(1), m.group(2)
            ln = line_of(scan, m.start())
            resolved = _resolve_citation(cfg, path, target)
            if resolved is None:
                if unfinished_milestone and lines[ln - 1].startswith("**Evidence of exit:**"):
                    out.append(Finding("W005", r, ln, f"evidence file not written yet: {target}"))
                elif bootstrapping and _under_docs(cfg, path, target):
                    out.append(Finding("W007", r, ln, f"cited file not written yet (bootstrap in progress): {target}"))
                else:
                    out.append(Finding("E001", r, ln, f"cited file missing: {target}"))
                continue
            if anchor:
                if resolved not in heading_cache:
                    try:
                        heading_cache[resolved] = numbered_anchors(read_text(resolved))
                    except UnreadableFile:
                        heading_cache[resolved] = set()
                if anchor not in heading_cache[resolved]:
                    out.append(Finding("E002", r, ln, f"no heading §{anchor} in {target}"))
    return out


# --------------------------------------------------------------------------- checks: status agreement


def check_status_agreement(project: Project) -> list[Finding]:
    cfg = project.cfg
    out: list[Finding] = []
    for pl in project.plans.values():
        r = rel(cfg, pl.path)
        hit = project.feature_of(pl.id)
        if pl.status == "moved":
            if not pl.moved_to or project.feature_of(pl.moved_to) is None:
                out.append(Finding("E010", r, 1, f"moved pointer does not resolve: {pl.moved_to or '(none)'}"))
            continue
        if hit is None:
            out.append(Finding("E006", r, 1, f"plan {pl.id} has no feature line in any milestone"))
            continue
        m, f = hit
        if f.moved_to:
            continue
        if pl.status == "done" and not f.ticked:
            out.append(Finding("E006", rel(cfg, m.path), f.line, f"{f.id} plan is done but feature is unticked"))
        if f.ticked and pl.status != "done":
            out.append(Finding("E006", rel(cfg, m.path), f.line, f"{f.id} feature is ticked but plan is '{pl.status}'"))
    for m in project.milestones.values():
        r = rel(cfg, m.path)
        for f in m.features:
            if f.moved_to and project.feature_of(f.moved_to) is None:
                out.append(Finding("E010", r, f.line, f"{f.id} moved pointer does not resolve: {f.moved_to}"))
            if f.ticked and not f.moved_to and f.id not in project.plans:
                out.append(Finding("E006", r, f.line, f"{f.id} is ticked but has no plan"))
        if m.status in ACTIVE_MILESTONE_STATUSES and not m.exit_criteria:
            out.append(Finding("E009", r, 1, f"{m.id} is '{m.status}' but has no exit criteria"))
        if m.status == "done":
            for f in m.features:
                if not f.moved_to and not f.ticked:
                    out.append(Finding("E007", r, f.line, f"{m.id} is done but {f.id} is unticked"))
            if not m.evidence:
                out.append(Finding("E007", r, 1, f"{m.id} is done but has no evidence link"))
    return out


# --------------------------------------------------------------------------- checks: dependencies


def _dep_status(project: Project, dep: str) -> str | None:
    """Status of the milestone that a dependency (M3 or M3-02) belongs to; None if unknown."""
    if "-" in dep:
        hit = project.feature_of(dep)
        return hit[0].status if hit else None
    return project.status_of(dep)


def check_dependencies(project: Project) -> list[Finding]:
    cfg = project.cfg
    out: list[Finding] = []
    for m in project.milestones.values():
        if m.status not in ("planned", "in progress"):
            continue
        r = rel(cfg, m.path)
        for dep in m.depends_on:
            st = _dep_status(project, dep)
            if st in (None, "sketch", "dropped"):
                out.append(Finding("E008", r, 1, f"{m.id} depends on {dep} which is {st or 'unknown'}"))
        for f in m.features:
            for dep in f.depends_on:
                st = _dep_status(project, dep)
                if st in (None, "sketch", "dropped"):
                    out.append(Finding("E008", r, f.line, f"{f.id} depends on {dep} which is {st or 'unknown'}"))
    for pl in project.plans.values():
        if pl.status != "in progress":
            continue
        hit = project.feature_of(pl.id)
        deps = list(pl.depends_on) + (hit[1].depends_on if hit else [])
        for dep in deps:
            if "-" not in dep:
                continue
            target = project.feature_of(dep)
            if target and not target[1].ticked:
                out.append(Finding("W002", rel(cfg, pl.path), 1, f"{pl.id} is in progress but dependency {dep} is unticked"))
    return out


# --------------------------------------------------------------------------- checks: placeholders

TBD_RE = re.compile(r"\bTBD\b")


def _in_placeholder_scope(cfg: Config, relpath: str) -> bool:
    return relpath.startswith("docs/") or relpath in PLACEHOLDER_SCOPE_ROOT_FILES


def check_placeholders(project: Project) -> list[Finding]:
    cfg = project.cfg
    out: list[Finding] = []
    allowed = [a.strip("/") for a in cfg.allow_tbd_in]
    sketch = project.roadmap.sketch_ranges if project.roadmap else []
    roadmap_rel = rel(cfg, project.roadmap.path) if project.roadmap else None
    for path in project.md_files:
        r = rel(cfg, path)
        if not _in_placeholder_scope(cfg, r):
            continue
        if any(r == a or r.startswith(a + "/") for a in allowed):
            continue
        try:
            text = read_text(path)
        except UnreadableFile:
            continue  # already reported as E011 by check_citations
        if text.startswith(GENERATED_MARKER):
            continue
        for i, line in enumerate(text.split("\n"), start=1):
            if r == roadmap_rel and any(a <= i <= b for a, b in sketch):
                continue
            if "{{" in line:
                out.append(Finding("E005", r, i, "template placeholder '{{' left in doc"))
            if TBD_RE.search(line):
                out.append(Finding("E005", r, i, "TBD outside OPEN-QUESTIONS.md or a sketch section"))
            if cfg.codename_placeholder and cfg.codename_placeholder in line:
                out.append(Finding("E005", r, i, f"codename placeholder '{cfg.codename_placeholder}' left in doc"))
    return out


# --------------------------------------------------------------------------- checks: vocabulary, structure

ADR_SUPERSEDED_RE = re.compile(r"^superseded by \d{4}$")
DESIGN_STATUS_RE = re.compile(r"\*\*Status:\*\*[ \t]*([A-Za-z]+(?: [A-Za-z]+)*)")


def check_vocabulary(project: Project) -> list[Finding]:
    """E013: every `**Status:**` is one of the words layers.md §3 allows for that object. A
    status outside the vocabulary would otherwise silently drop the file out of every other
    check that keys on status."""
    cfg = project.cfg
    out: list[Finding] = []

    def bad(kind: str, status: str, allowed: tuple[str, ...]) -> str:
        shown = status or "(missing)"
        return f"{kind} status {shown!r} is not one of: {', '.join(allowed)}"

    for m in project.milestones.values():
        if m.status not in MILESTONE_STATUSES:
            out.append(Finding("E013", rel(cfg, m.path), 1, bad("milestone", m.status, MILESTONE_STATUSES)))
    for pl in project.plans.values():
        if pl.status not in PLAN_STATUSES:
            out.append(Finding("E013", rel(cfg, pl.path), 1, bad("plan", pl.status, PLAN_STATUSES)))
    for a in project.adrs:
        if a.status not in ADR_STATUSES and not ADR_SUPERSEDED_RE.match(a.status):
            out.append(Finding("E013", rel(cfg, a.path), 1,
                               bad("ADR", a.status, (*ADR_STATUSES, "superseded by NNNN"))))
    if project.roadmap:
        r = rel(cfg, project.roadmap.path)
        for p in project.roadmap.phases:
            if p.status not in PHASE_STATUSES:
                out.append(Finding("E013", r, p.line, bad(f"phase {p.id}", p.status, PHASE_STATUSES)))
    return out


def _design_docs(project: Project) -> list[Path]:
    out = []
    for path in project.md_files:
        r = rel(project.cfg, path)
        if (r.startswith("docs/design/") or r == "docs/design.md") and path.name != "README.md":
            out.append(path)
    return out


def check_design_docs(project: Project) -> list[Finding]:
    """E014: the header doc-kinds.md §3 requires (Project, Status, Audience) with a status in
    vocabulary. E015: a closing `## Changelog`."""
    cfg = project.cfg
    out: list[Finding] = []
    for path in _design_docs(project):
        r = rel(cfg, path)
        try:
            text = read_text(path)
        except UnreadableFile:
            continue  # already reported as E011
        if text.startswith(GENERATED_MARKER):
            continue
        has_header = all(f"**{k}:**" in text for k in ("Project", "Status", "Audience"))
        if not has_header:
            out.append(Finding("E014", r, 1, "design doc header missing (**Project:** / **Status:** / **Audience:**)"))
        else:
            sm = DESIGN_STATUS_RE.search(text)
            status = sm.group(1).strip().lower() if sm else ""
            if status not in DESIGN_STATUSES:
                out.append(Finding("E014", r, 1, f"design doc status {status!r} is not one of: {', '.join(DESIGN_STATUSES)}"))
        if not re.search(r"^## Changelog[ \t]*$", text, re.M):
            out.append(Finding("E015", r, 1, "design doc has no ## Changelog section"))
    return out


def check_sizes(project: Project) -> list[Finding]:
    """W004: a planned or in-progress milestone holds 3-10 features (layers.md §5). W006:
    AGENTS.md stays under 120 lines (lessons.md §1.17)."""
    cfg = project.cfg
    out: list[Finding] = []
    for m in project.milestones.values():
        if m.status not in ("planned", "in progress"):
            continue
        n = sum(1 for f in m.features if not f.moved_to)
        if not MILESTONE_MIN_FEATURES <= n <= MILESTONE_MAX_FEATURES:
            out.append(Finding("W004", rel(cfg, m.path), 1,
                               f"{m.id} has {n} feature(s); a milestone holds {MILESTONE_MIN_FEATURES}-{MILESTONE_MAX_FEATURES}"))
    agents = cfg.root / "AGENTS.md"
    if agents.is_file():
        try:
            n = len(read_text(agents).rstrip("\n").split("\n"))
        except UnreadableFile:
            n = 0
        if n > AGENTS_MAX_LINES:
            out.append(Finding("W006", "AGENTS.md", 1, f"AGENTS.md is {n} lines; keep it under {AGENTS_MAX_LINES}"))
    return out


def check_phases(project: Project) -> list[Finding]:
    """E016: at most one phase is active; an active phase states its exit; a done phase has
    only done or dropped milestones under it."""
    if not project.roadmap:
        return []
    cfg = project.cfg
    r = rel(cfg, project.roadmap.path)
    out: list[Finding] = []
    active = [p for p in project.roadmap.phases if p.status == "active"]
    for p in active[1:]:
        out.append(Finding("E016", r, p.line, f"{p.id} is active but {active[0].id} already is; one phase is active at a time"))
    for p in active:
        if not p.exit:
            out.append(Finding("E016", r, p.line, f"{p.id} is active but has no **Exit:** line"))
    for p in project.roadmap.phases:
        if p.status != "done":
            continue
        for mid in p.milestones:
            st = project.status_of(mid)
            if st not in ("done", "dropped"):
                out.append(Finding("E016", r, p.line, f"{p.id} is done but {mid} is {st or 'unknown'}"))
    return out


# --------------------------------------------------------------------------- checks: claims


def check_claims(project: Project, now: datetime | None = None) -> list[Finding]:
    cfg = project.cfg
    now = now or datetime.now(timezone.utc)
    out: list[Finding] = []
    for pl in project.plans.values():
        if pl.status != "in progress":
            continue
        r = rel(cfg, pl.path)
        if not pl.stamps:
            out.append(Finding("W001", r, 1, f"{pl.id} is in progress with no session stamp under ## Sessions"))
            continue
        latest = max(dt for dt, _ in pl.stamps)
        if now - latest > timedelta(hours=cfg.stale_hours):
            age_h = (now - latest).total_seconds() / 3600
            out.append(Finding("W001", r, 1, f"{pl.id} claim is stale: last stamp {latest.isoformat()} ({age_h:.0f}h ago)"))
    return out


# --------------------------------------------------------------------------- generators


def gen_milestones_index(project: Project) -> str:
    lines = [GENERATED_MARKER, "# Milestones", "",
             "| ID | Title | Status | Features done |", "|---|---|---|---|"]
    for mid in project.milestone_order():
        m = project.milestones.get(mid)
        if m:
            real = [f for f in m.features if not f.moved_to]
            done = sum(1 for f in real if f.ticked)
            lines.append(f"| {m.id} | {m.title} | {m.status} | {done}/{len(real)} |")
        else:
            title = project.roadmap.milestone_titles.get(mid, "") if project.roadmap else ""
            lines.append(f"| {mid} | {title} | sketch | — |")
    return "\n".join(lines) + "\n"


def gen_plans_index(project: Project) -> str:
    lines = [GENERATED_MARKER, "# Plans", ""]
    for mid in project.milestone_order():
        m = project.milestones.get(mid)
        if not m:
            continue
        plans = sorted((p for p in project.plans.values() if p.milestone == mid), key=lambda p: p.id)
        if not plans:
            continue
        lines += [f"## {mid} — {m.title}", ""]
        active = [p for p in plans if p.status not in ("done", "moved", "superseded")]
        closed = [p for p in plans if p.status in ("done", "moved", "superseded")]
        for p in active:
            lines.append(f"- {p.id} — {p.title} — `{rel(project.cfg, p.path)}` — {p.status}")
        if closed:
            lines += ["", "<details><summary>Closed</summary>", ""]
            for p in closed:
                extra = f" → {p.moved_to}" if p.moved_to else ""
                lines.append(f"- {p.id} — {p.title} — `{rel(project.cfg, p.path)}` — {p.status}{extra}")
            lines += ["", "</details>"]
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def gen_decisions_index(project: Project) -> str:
    lines = [GENERATED_MARKER, "# Architecture Decision Records", "",
             "| # | Decision | Status |", "|---|---|---|"]
    for a in project.adrs:
        lines.append(f"| {a.number} | [{a.title}]({a.path.name}) | {a.status} |")
    return "\n".join(lines) + "\n"


CLAIMED_CAP = 6
BLOCKED_CAP = 4
NEXT_CAP = 6
QUESTIONS_CAP = 4
EVIDENCE_CAP = 3


def open_questions(cfg: Config) -> list[tuple[str, list[str]]]:
    """(question, blocked IDs) per row of docs/OPEN-QUESTIONS.md; empty if the file is absent."""
    path = cfg.docs / "OPEN-QUESTIONS.md"
    if not path.is_file():
        return []
    try:
        text = read_text(path)
    except UnreadableFile:
        return []
    rows: list[tuple[str, list[str]]] = []
    for line in text.split("\n"):
        if not line.startswith("|") or line.startswith("|---"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 3 or cells[0].lower() == "question":
            continue
        rows.append((cells[0], parse_ids(cells[2])))
    return rows

EVIDENCE_ID_RE = re.compile(r"^M(\d+)")


def _evidence_sort_key(p: Path) -> tuple[int, str]:
    """Numeric key by leading M<digits> in the filename; non-matching names sort after, by name."""
    m = EVIDENCE_ID_RE.match(p.stem)
    return (int(m.group(1)), p.name) if m else (10**9, p.name)


def _capped_front(items: list[str], cap: int) -> list[str]:
    """First `cap` lines; the last one becomes a summary when the list is longer than cap."""
    if len(items) <= cap:
        return items
    shown = items[: cap - 1]
    return shown + [f"- … and {len(items) - len(shown)} more"]


def _capped_latest(items: list[str], cap: int) -> list[str]:
    """Most recent `cap` lines; a summary of the rest is prepended when truncated."""
    if len(items) <= cap:
        return items
    shown = items[-(cap - 1):]
    return [f"- … and {len(items) - len(shown)} more"] + shown


def gen_current(project: Project) -> str:
    cfg = project.cfg
    lines = [GENERATED_MARKER, "# Current focus", ""]
    active_phases = [p for p in (project.roadmap.phases if project.roadmap else []) if p.status == "active"]
    if active_phases:
        lines.append("**Phase:** " + "; ".join(f"{p.id} — {p.title}" for p in active_phases))
    in_prog = [project.milestones[m] for m in project.milestone_order()
               if m in project.milestones and project.milestones[m].status == "in progress"]
    listed = list(in_prog)
    if in_prog:
        lines.append("**Milestones in progress:** " + "; ".join(f"{m.id} — {m.title}" for m in in_prog))
        for m in in_prog:
            if m.exit_criteria:
                lines.append(f"**Exit ({m.id}):** {m.exit_criteria}")
    else:
        planned = [project.milestones[m] for m in project.milestone_order()
                   if m in project.milestones and project.milestones[m].status == "planned"]
        if planned:
            listed = planned[:1]
            lines.append(f"**Next milestone:** {planned[0].id} — {planned[0].title} (planned)")
    lines.append("")

    claimed = sorted((p for p in project.plans.values() if p.status == "in progress"), key=lambda p: p.id)
    claimed_lines = []
    for p in claimed:
        if p.stamps:
            dt, agent = max(p.stamps)
            stamp = dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%MZ") + f" ({agent})"
        else:
            stamp = "no stamp"
        note = f" — last note: {p.last_note}" if p.last_note else ""
        claimed_lines.append(f"- {p.id} — {p.title} — `{rel(cfg, p.path)}` — {stamp}{note}")
    lines += ["## Claimed features", ""]
    lines += _capped_front(claimed_lines, CLAIMED_CAP) if claimed_lines else ["- none"]

    blocked = sorted((p for p in project.plans.values() if p.status == "blocked"), key=lambda p: p.id)
    if blocked:
        blocked_lines = [f"- {p.id} — {p.title} — `{rel(cfg, p.path)}`" for p in blocked]
        lines += ["", "## Blocked", ""]
        lines += _capped_front(blocked_lines, BLOCKED_CAP)

    nxt = []
    nxt_ids: list[str] = []
    for m in listed:
        for f in m.features:
            if f.ticked or f.moved_to:
                continue
            pl = project.plans.get(f.id)
            if pl is None or pl.status in ("grounding", "planned"):
                nxt.append(f"- {f.id} — {f.title}")
                nxt_ids.append(f.id)
    lines += ["", "## Next unclaimed features", ""]
    lines += _capped_front(nxt, NEXT_CAP) if nxt else ["- none"]

    visible = set(nxt_ids) | {p.id for p in claimed} | {m.id for m in listed}
    blocking = []
    for question, ids in open_questions(cfg):
        hit = next((i for i in ids if i in visible), None)
        if hit:
            blocking.append(f"- {hit} — {question}")
    if blocking:
        lines += ["", "## Blocking questions", ""]
        lines += _capped_front(blocking, QUESTIONS_CAP)

    ev_dir = cfg.docs / "evidence"
    evidence = sorted(ev_dir.glob("*.md"), key=_evidence_sort_key) if ev_dir.is_dir() else []
    if evidence:
        evidence_lines = [f"- `{rel(cfg, p)}`" for p in evidence]
        lines += ["", "## Latest evidence", ""]
        lines += _capped_latest(evidence_lines, EVIDENCE_CAP)
    return "\n".join(lines) + "\n"


def generate(project: Project) -> dict[str, str]:
    out: dict[str, str] = {}
    if project.tier in STANDARD_LIKE:
        out["docs/milestones/README.md"] = gen_milestones_index(project)
        out["docs/plans/README.md"] = gen_plans_index(project)
        out["docs/CURRENT.md"] = gen_current(project)
    if project.tier in (*STANDARD_LIKE, "lite") and (project.cfg.docs / "decisions").is_dir():
        out["docs/decisions/README.md"] = gen_decisions_index(project)
    return out


# --------------------------------------------------------------------------- checks: generated files


def check_generated(project: Project) -> list[Finding]:
    cfg = project.cfg
    out: list[Finding] = []
    for relp, expected in generate(project).items():
        path = cfg.root / relp
        try:
            actual = read_text(path) if path.is_file() else None
        except UnreadableFile:
            actual = None
        if relp.endswith("milestones/README.md"):
            for row in expected.split("\n"):
                if row.startswith("| M") and (actual is None or row not in actual):
                    out.append(Finding("E003", relp, 1, f"milestone index missing or stale for row: {row}"))
        elif relp.endswith("decisions/README.md"):
            for a in project.adrs:
                if actual is None or f"| {a.number} |" not in actual:
                    out.append(Finding("E004", relp, 1, f"ADR {a.number} missing from index"))
        if actual != expected and not any(f.path == relp and f.is_error for f in out):
            out.append(Finding("W003", relp, 1, "generated file differs from --fix output; run check_docs.py --fix"))
    return out


# --------------------------------------------------------------------------- run / main


def run(root: Path, fix: bool = False, stale_hours: float | None = None) -> list[Finding]:
    cfg = load_config(Path(root))
    if stale_hours is not None:
        cfg.stale_hours = stale_hours
    project = load_project(cfg)
    if fix:
        # Generate first, then check, so the first run of a fresh project does not report the
        # files it is about to write as missing.
        for relp, content in generate(project).items():
            path = cfg.root / relp
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
        project = load_project(cfg)
    return check(project)


def check(project: Project, now: datetime | None = None) -> list[Finding]:
    cfg = project.cfg
    findings: list[Finding] = []
    if cfg.config_error:
        findings.append(Finding("E012", "docs/.check_docs.toml", 1,
                                 f"invalid config: {cfg.config_error}"))
    findings += project.load_errors
    findings += check_citations(cfg, project.md_files)
    findings += check_placeholders(project)
    findings += check_design_docs(project)
    findings += check_sizes(project)
    if project.tier in STANDARD_LIKE:
        findings += check_vocabulary(project)
        findings += check_status_agreement(project)
        findings += check_dependencies(project)
        findings += check_phases(project)
        findings += check_claims(project, now)
    findings += check_generated(project)
    return findings


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Doc linter and index generator.")
    ap.add_argument("--root", default=".", help="project root (default: current directory)")
    ap.add_argument("--fix", action="store_true", help="regenerate index files and CURRENT.md")
    ap.add_argument("--stale-hours", type=float, default=None, help="claim staleness threshold")
    args = ap.parse_args(argv)
    findings = run(Path(args.root).resolve(), fix=args.fix, stale_hours=args.stale_hours)
    for f in sorted(findings, key=lambda f: (f.path, f.line, f.code)):
        print(f)
    n_err = sum(1 for f in findings if f.is_error)
    n_warn = len(findings) - n_err
    print(f"{n_err} error(s), {n_warn} warning(s)")
    return 1 if n_err else 0


if __name__ == "__main__":
    sys.exit(main())
